services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant_db
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./qdrant_storage:/qdrant/storage
    restart: always

  rag-app:
    build: .
    container_name: rag_app
    depends_on:
      - qdrant
    env_file:
      - .env
    volumes:
      - .:/app
    restart: on-failure
